name: CD BACKEND NEOS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy Docker image to backend servers
        uses: appleboy/ssh-action@master
        env:
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          BACKEND_IP_1: ${{ secrets.PRIVATE_IP_1 }}
          BACKEND_IP_2: ${{ secrets.PRIVATE_IP_2 }}
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Adicionar as chaves das máquinas privadas ao known_hosts
            ssh-keyscan -H $BACKEND_IP_1 >> ~/.ssh/known_hosts
            ssh-keyscan -H $BACKEND_IP_2 >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts

            echo "${{ secrets.SSH_PRIVATE_KEY }}" > blume_key.pem
  
            # Conectar à máquina privada 1 e atualizar o Docker
            ssh -i blume_key.pem ubuntu@$BACKEND_IP_1 << 'PRIVATE_EOF'
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm
              sudo docker pull victorlcdpaula/backend-neos:latest
              sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest
            PRIVATE_EOF
  
            # Conectar à máquina privada 2 e atualizar o Docker
            ssh -i blume_key.pem ubuntu@$BACKEND_IP_2 << 'PRIVATE_EOF'
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm
              sudo docker pull victorlcdpaula/backend-neos:latest
              sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest
            PRIVATE_EOF

      - name: Clean up private key
        run: |
          rm -f ~/.ssh/blume_key.pem
