name: CD BACKEND NEOS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Etapa para limpar chave EC2 existente
      - name: Cleanup existing EC2 keypair (if any)
        run: |
          aws ec2 delete-key-pair --key-name blume_key || echo "No key pair to delete"

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/blume_key.pem

          # Salvar a chave privada do GitHub Secrets em um arquivo temporário
          chmod 600 ~/.ssh/blume_key.pem
          chmod 644 ~/.ssh/blume_key.pem.pub

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: Deploy Docker image to backend servers
        env:
          JUMP_SERVER: ${{ secrets.PUBLIC_IP }}
          BACKEND_IP_1: ${{ secrets.PRIVATE_IP_1 }}
          BACKEND_IP_2: ${{ secrets.PRIVATE_IP_2 }}
        run: |
          # Copiar a chave privada para o jump server
          scp -i ~/.ssh/blume_key.pem ~/.ssh/blume_key.pem $PUBLIC_IP:/home/ubuntu/
          scp -i ~/.ssh/blume_key.pem.pub ~/.ssh/blume_key.pem.pub $PUBLIC_IP:/home/ubuntu/

          # Conectar ao primeiro backend via jump server (frontend) usando ProxyJump
          ssh -i ~/.ssh/blume_key.pem -o StrictHostKeyChecking=no -J $PUBLIC_IP ubuntu@$BACKEND_IP_1 <<EOF
            sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
            sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm
            sudo docker pull victorlcdpaula/backend-neos:latest
            sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest
          EOF

          # Conectar ao segundo backend via jump server (frontend) usando ProxyJump
          ssh -i ~/.ssh/blume_key.pem -o StrictHostKeyChecking=no -J $PUBLIC_IP ubuntu@$BACKEND_IP_2 <<EOF
            sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
            sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm
            sudo docker pull victorlcdpaula/backend-neos:latest
            sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest
          EOF

      - name: Clean up private key
        run: |
          rm -f ~/.ssh/blume_key.pem
