name: CD BACKEND NEOS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/blume_key.pem
          chmod 400 ~/.ssh/blume_key.pem

      - name: Deploy Docker image to backend servers
        env:
          JUMP_SERVER: ${{ secrets.PUBLIC_IP }}
          BACKEND_IP_1: ${{ secrets.PRIVATE_IP_1 }}
          BACKEND_IP_2: ${{ secrets.PRIVATE_IP_2 }}
        run: |
          # Definir o comando SSH com ProxyJump
          SSH_CMD="ssh -i ~/.ssh/blume_key.pem -o StrictHostKeyChecking=no -J ubuntu@$JUMP_SERVER"

          for BACKEND in $BACKEND_IP_1 $BACKEND_IP_2; do
            echo "Deploying to $BACKEND..."
            
            $SSH_CMD ubuntu@$BACKEND << 'EOF'
              # Remover containers e imagens antigos
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
              sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm

              # Baixar a nova imagem e rodar o container
              sudo docker pull victorlcdpaula/backend-neos:latest
              sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest
              EOF
          done

      - name: Clean up private key
        run: |
          rm -f ~/.ssh/blume_key.pem
