name: CD BACKEND NEOS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH for frontend and backend
        run: |
          mkdir -p ~/.ssh
        
          # Salvar a chave privada em um arquivo temporário
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/blume_key.pem
          
          # Definir permissões de acesso corretas para a chave privada
          chmod 400 ~/.ssh/blume_key.pem
          cd ~/.ssh/

      - name: Deploy Docker image to both backends via jump server
        env:
          PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
          BACKEND_IP_1: ${{ secrets.PRIVATE_IP_1 }}
          BACKEND_IP_2: ${{ secrets.PRIVATE_IP_2 }}
        run: |
          # Conectar ao primeiro backend via jump server (frontend) usando ProxyJump
          scp -i ~/.ssh/blume_key.pem blume_key.pem $PUBLIC_IP:/home/ubuntu/
          ssh -i ~/.ssh/blume_key.pem $PUBLIC_IP

          ssh -i blume_key.pem $BACKEND_IP_1

          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest --format "{{.ID}}"
          
          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm


          sudo docker pull victorlcdpaula/backend-neos:latest
          sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest

          exit

          ssh -i blume_key.pem $BACKEND_IP_2

          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest --format "{{.ID}}"

          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker stop
          sudo docker ps -a --filter ancestor=victorlcdpaula/backend-neos:latest -q | xargs -r sudo docker rm

          sudo docker pull victorlcdpaula/backend-neos:latest
          sudo docker run -d -p 8080:8080 victorlcdpaula/backend-neos:latest

          exit
          exit

      - name: Clean up private key
        run: |
          rm -f ~/.ssh/blume_key.pem
